### ISSUE TITLE
Disable timeout

### ISSUE THREAD

**Issue by williamFalcon** [Lightning-AI/litserve#52]
how do you disable it?

also, add a nice message when something times out to let the user there is a timeout argument that has been defaulted to 30

```bash
A request timedout. current timeout set to 30.
change timeout by LitServe(..., timeout=30)
```

**Comment by aniketmaurya** [comment]
we can log a msg on server side instead of sending this to client.

```py
logging.error("Server couldn't process request within the specified timeout"
                              "current timeout set to 30. change timeout by LitServe(..., timeout=30)")
raise HTTPException(status_code=504, detail="Request timed out")
```

**Comment by lantiga** [comment]
Let's support `timeout=-1` or `timeout=False` (default stays `30`) to support cases with long running requests.

The other thing we need to do (both for `timeout=False` and `timeout > 0`) is avoid disconnecting due to timeout for a client whose prediction is currently being ran. That is, we should only apply it for clients that are waiting in the queue. That is because timeout currently never cancels a prediction that is ongoing, but only evicts requests from the queue.

In the future we can have better heuristics on how to automatically tune timeout but it's something for later.

**Comment by lantiga** [comment]
One last thing is to plan for a non-blocking mode, where we tell `LitServe` that `predict` will return a token and we can use that token later to check the result (a-la message queue).

This way we can have the client expose a callback to be called when the results are available.

This is particularly useful when we foresee that preditions will be long-running (case in point, applying whisper on a 15-mins podcast).
