### ISSUE TITLE
default unbatch is always a generator

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/litserve#66]
## 🐛 Bug

Since `LitAPI.unbatch` has an `yield` statement, it is always considered as a generator even if the line is not executed. [[Reference](https://stackoverflow.com/questions/26595895/return-and-yield-in-the-same-function)]

This is causing the server to fail silently with dynamic batching.

**Comment by lantiga** [comment]
When you instantiate the server (in its init), you have the API instance and you also know if you need to stream. At that point you can call a function in API that will assign the right function to the batch method.

This way there will be no codepath in which yield exist if streaming is false. You can do this because everything is known at construction time and it is not supposed to change.

**Comment by aniketmaurya** [comment]
thank you @lantiga for the input. I have created a fix.
